name: MultipleRespawnLocation
version: '${project.version}'
main: fr.laboulangerie.multiplerespawnlocation.MultipleRespawnLocation
api-version: 1.19
softdepend: [Minelet, MultiSpawn]
authors: [Gabi, LaBoulangerie, Red69_Leaf]
description: Allow players to save multiple bed spawn points and choose where to respawn. Supports Minelet hamlet spawns.
website: https://github.com/LaBoulworkaround/MultipleRespawnLocation
permissions:
  multiplebedspawn.skipcooldown:
    description: Allows the player to skip the bed's respawn cooldown
    default: false
  multiplebedspawn.maxcount.*:
    description: Allows to set custom max number of beds (ignores the config)
    default: false
